## Backpropgation _ Regression using Keras

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.DataFrame([[8, 8, 4], [7, 5, 9], [6, 10, 6], [5, 12, 7]], columns=['cgpa', 'profile_score', 'lpa'])
df

,cgpa,profile_score,lpa
0,8,8,4
1,7,5,9
2,6,10,6
3,5,12,7


In [3]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [4]:
model = Sequential()

model.add(Dense(2, activation='linear', input_dim=2))
model.add(Dense(1, activation='linear'))

c:\Users\alili\100_days_Deep_Learning\.venv\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [5]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 2)              │             6 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [6]:
model.get_weights()

[array([[ 1.136211  , -0.17493808],
        [-0.02094913, -0.60966355]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[ 0.8773805],
        [-0.9790035]], dtype=float32),
 array([0.], dtype=float32)]

In [7]:
optimizer = keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss='mean_squared_error', optimizer=optimizer)

In [8]:
model.fit(df.iloc[:, 0: -1].values, df['lpa'].values, epochs=90, verbose=1, batch_size=1)

Epoch 1/90
4/4 ━━━━━━━━━━━━━━━━━━━━ 2s 51ms/step - loss: 45.2857
Epoch 2/90
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 43.1824 
Epoch 3/90
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 41.2394
Epoch 4/90
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 39.5013
Epoch 5/90
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 37.7184
Epoch 6/90
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 35.8711
Epoch 7/90
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 34.4447
Epoch 8/90
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 32.8646
Epoch 9/90
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 31.1940
Epoch 10/90
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 30.0006
Epoch 11/90
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 28.6746
Epoch 12/90
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 27.5087
Epoch 13/90
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 26.3871
Epoch 14/90
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 24.9306
Epoch 15/90
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 23.8981
Epoch 16/90
4/4 ━━