## Backpropagation for Classification - Keras

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.DataFrame([[8,8,1],[7,9,1],[6,10,0],[5,5,0]], columns=['cgpa', 'profile_score', 'placed'])

In [3]:
df.head()

,cgpa,profile_score,placed
0,8,8,1
1,7,9,1
2,6,10,0
3,5,5,0


In [4]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [5]:
model = Sequential()

model.add(Dense(2, activation='sigmoid', input_dim=2))
model.add(Dense(1, activation='sigmoid'))

c:\Users\alili\100_days_Deep_Learning\.venv\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [6]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 2)              │             6 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [7]:
model.get_weights()

[array([[-1.0652827 ,  0.90382636],
        [-1.1535002 ,  0.32316935]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[-1.4004177 ],
        [ 0.58631957]], dtype=float32),
 array([0.], dtype=float32)]

In [8]:
optimizer = keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss='binary_crossentropy', optimizer=optimizer)

In [10]:
model.fit(df.iloc[:, 0: -1].values, df['placed'].values, epochs=60, verbose=1, batch_size=1)

Epoch 1/60


4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.7215
Epoch 2/60
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 0.7212 
Epoch 3/60
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.7208
Epoch 4/60
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.7208
Epoch 5/60
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.7205
Epoch 6/60
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.7202 
Epoch 7/60
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.7197
Epoch 8/60
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.7195
Epoch 9/60
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.7191 
Epoch 10/60
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 0.7189 
Epoch 11/60
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.7188 
Epoch 12/60
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.7185
Epoch 13/60
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.7183
Epoch 14/60
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.7180
Epoch 15/60
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 0.7180
Epoch 16/60
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 